name: Build Standalone Apps
on: [push]
jobs:
  binary:
    runs-on: ${{ matrix.os.version }}
    strategy:
      matrix:
        python-version: [3.7, 3.8, 3.9]
        os: 
          - version: macos-latest
            name: macos
          - version: ubuntu-latest
            name: ubuntu
          - version: windows-latest
            name: windows
    steps:
      - uses: actions/checkout@v2
      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v2
        with:
          python-version: ${{ matrix.python-version }}
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install pyinstaller
      - name: Build with PyInstaller
        run: python -OO -m PyInstaller --onefile --name brp batchrenamer/__main__.py
      - name: Upload build to release
        uses: svenstaro/upload-release-action@v2
        with:
          repo_token: ${{ secrets.GITHUB_TOKEN }}
          file: dist/brp
          asset_name: brp-${{ matrix.os.name }}-${{ matrix.python-version }}
          tag: ${{ github.ref }}
