name: Build Standalone Apps
on: 
  push:
    tags:
      - '*'
jobs:
  binary:
    runs-on: ${{ matrix.os.version }}
    strategy:
      matrix:
        os: 
          - version: macos-latest
            name: macos
            output: brp
          - version: ubuntu-latest
            name: ubuntu
            output: brp
          - version: windows-latest
            name: windows
            output: brp.exe
    steps:
      - uses: actions/checkout@v2
      - name: Set up Python 3.9
        uses: actions/setup-python@v2
        with:
          python-version: 3.9
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install pyinstaller
      - name: Build with PyInstaller
        run: python -OO -m PyInstaller --onefile --name brp batchrenamer/__main__.py
      - name: Upload build to release
        uses: svenstaro/upload-release-action@v2
        with:
          repo_token: ${{ secrets.GITHUB_TOKEN }}
          file: dist/${{ matrix.os.output }}
          asset_name: ${{ matrix.os.name }}-${{ matrix.os.output }}
          overwrite: true
          tag: ${{ github.ref }}
